import type { Achievement, CustomerType, MascotState, Product, ShopEvent } from "@/types/homefarm-shop";

export const ALL_PRODUCTS: Product[] = [
  // Day 1-5: core calm mode, 8 items only
  { id: "salmon", name: "Cá hồi", icon: "🐟", stock: 12.4, unit: "kg", price: 769, cost: 520, unlockDay: 1, category: "seafood" },
  { id: "wholeSalmon", name: "Cá nguyên", icon: "🎣", stock: 3, unit: "con", price: 559 * 6, cost: 430 * 6, unlockDay: 1, category: "seafood" },
  { id: "beef", name: "Bò Mỹ", icon: "🥩", stock: 8.6, unit: "kg", price: 429, cost: 260, unlockDay: 1, category: "meat" },
  { id: "egg", name: "Trứng", icon: "🥚", stock: 18, unit: "hộp", price: 69, cost: 42, unlockDay: 1, category: "core" },
  { id: "sausage", name: "Xúc xích", icon: "🌭", stock: 16, unit: "gói", price: 89, cost: 55, unlockDay: 1, category: "addon" },
  { id: "grape", name: "Nho Mỹ", icon: "🍇", stock: 7.8, unit: "kg", price: 199, cost: 125, unlockDay: 1, category: "fruit" },
  { id: "cherry", name: "Cherry", icon: "🍒", stock: 4.4, unit: "kg", price: 459, cost: 310, unlockDay: 1, category: "fruit" },
  { id: "headBone", name: "Đầu xương", icon: "🍲", stock: 2.2, unit: "kg", price: 89, cost: 0, unlockDay: 1, category: "addon" },

  // From day 6 onward: +2 products every 2 days, max 32 items
  { id: "shrimp", name: "Tôm sú", icon: "🦐", stock: 4.5, unit: "kg", price: 329, cost: 220, unlockDay: 6, category: "seafood" },
  { id: "squid", name: "Mực", icon: "🦑", stock: 4.2, unit: "kg", price: 259, cost: 175, unlockDay: 6, category: "seafood" },

  { id: "pork", name: "Heo Iberico", icon: "🥓", stock: 5.5, unit: "kg", price: 359, cost: 230, unlockDay: 8, category: "meat" },
  { id: "sashimi", name: "Set sashimi", icon: "🍣", stock: 5, unit: "set", price: 299, cost: 195, unlockDay: 8, category: "seafood" },

  { id: "avocado", name: "Bơ", icon: "🥑", stock: 5, unit: "kg", price: 169, cost: 105, unlockDay: 10, category: "fruit" },
  { id: "blueberry", name: "Việt quất", icon: "🫐", stock: 3.5, unit: "hộp", price: 139, cost: 88, unlockDay: 10, category: "fruit" },

  { id: "cheese", name: "Phô mai", icon: "🧀", stock: 8, unit: "gói", price: 119, cost: 72, unlockDay: 12, category: "addon" },
  { id: "milk", name: "Sữa tươi", icon: "🥛", stock: 10, unit: "chai", price: 49, cost: 30, unlockDay: 12, category: "core" },

  { id: "oyster", name: "Hàu", icon: "🦪", stock: 4, unit: "kg", price: 219, cost: 145, unlockDay: 14, category: "seafood" },
  { id: "crab", name: "Cua", icon: "🦀", stock: 3.5, unit: "kg", price: 499, cost: 340, unlockDay: 14, category: "seafood" },

  { id: "boCanada", name: "Bò Canada", icon: "🥩", stock: 4, unit: "kg", price: 589, cost: 385, unlockDay: 16, category: "meat" },
  { id: "pizza", name: "Pizza", icon: "🍕", stock: 5, unit: "cái", price: 249, cost: 160, unlockDay: 16, category: "addon" },

  { id: "strawberry", name: "Dâu tây", icon: "🍓", stock: 4.2, unit: "kg", price: 299, cost: 195, unlockDay: 18, category: "fruit" },
  { id: "kiwi", name: "Kiwi", icon: "🥝", stock: 5, unit: "kg", price: 169, cost: 108, unlockDay: 18, category: "fruit" },

  { id: "butter", name: "Bơ lạt", icon: "🧈", stock: 8, unit: "hộp", price: 99, cost: 62, unlockDay: 20, category: "addon" },
  { id: "yogurt", name: "Sữa chua", icon: "🥣", stock: 10, unit: "hộp", price: 59, cost: 36, unlockDay: 20, category: "core" },

  { id: "scallop", name: "Sò điệp", icon: "🐚", stock: 3.2, unit: "kg", price: 459, cost: 315, unlockDay: 22, category: "seafood" },
  { id: "cod", name: "Cá tuyết", icon: "🐠", stock: 3.8, unit: "kg", price: 399, cost: 270, unlockDay: 22, category: "seafood" },

  { id: "wagyu", name: "Wagyu", icon: "🥩", stock: 2.5, unit: "kg", price: 1299, cost: 920, unlockDay: 24, category: "meat" },
  { id: "bacon", name: "Bacon", icon: "🥓", stock: 7, unit: "gói", price: 129, cost: 78, unlockDay: 24, category: "meat" },

  { id: "mango", name: "Xoài Úc", icon: "🥭", stock: 5, unit: "kg", price: 189, cost: 118, unlockDay: 26, category: "fruit" },
  { id: "orange", name: "Cam", icon: "🍊", stock: 6, unit: "kg", price: 129, cost: 78, unlockDay: 26, category: "fruit" },

  { id: "ham", name: "Jambon", icon: "🍖", stock: 8, unit: "gói", price: 109, cost: 68, unlockDay: 28, category: "addon" },
  { id: "bread", name: "Bánh mì", icon: "🥖", stock: 12, unit: "ổ", price: 39, cost: 22, unlockDay: 28, category: "core" },
];

export const START_PRODUCTS = ALL_PRODUCTS.filter((p) => (p.unlockDay || 1) <= 1);

const BASE_CUSTOMER_TYPES: CustomerType[] = [
  { name: "Mẹ đảm", avatar: "👩‍🍳", mood: "Soi kỹ", patience: 24, size: 4, prefer: ["salmon", "beef", "egg", "sashimi"], quote: "Cá phải tươi, thịt phải đẹp." },
  { name: "Gym Bro", avatar: "💪", mood: "Protein", patience: 26, size: 3, prefer: ["beef", "egg", "salmon", "sashimi", "wagyu"], quote: "Full protein cho anh." },
  { name: "Gen Z", avatar: "🧋", mood: "Ăn clean", patience: 36, size: 3, prefer: ["salmon", "grape", "cherry", "avocado", "blueberry", "yogurt"], quote: "Set healthy xinh xinh nha!" },
  { name: "Khách VIP", avatar: "😎", mood: "Chi mạnh", patience: 22, size: 5, prefer: ["salmon", "beef", "cherry", "shrimp", "wagyu", "crab"], quote: "Lấy đồ ngon nhất." },
  { name: "Khó tính", avatar: "😤", mood: "Gắt", patience: 16, size: 4, prefer: ["salmon", "beef", "wagyu"], quote: "Nhanh lên." },
  { name: "Dễ tính", avatar: "😊", mood: "Chill", patience: 42, size: 2, prefer: ["egg", "sausage", "grape", "milk", "bread"], quote: "Từ từ cũng được." },
  { name: "Gia đình", avatar: "👨‍👩‍👧", mood: "Mua nhiều", patience: 30, size: 5, prefer: ["salmon", "beef", "egg", "sausage", "pizza", "orange"], quote: "Mỗi thứ một ít." },
  { name: "Dân văn phòng", avatar: "💼", mood: "Ăn trưa", patience: 28, size: 3, prefer: ["sausage", "egg", "beef", "milk", "bread"], quote: "Nhanh gọn nhé." },
  { name: "Foodie", avatar: "🤤", mood: "Sành ăn", patience: 25, size: 4, prefer: ["salmon", "beef", "cherry", "cheese", "oyster", "scallop"], quote: "Phải ngon nhé." },
  { name: "Sinh viên", avatar: "🎓", mood: "Tiết kiệm", patience: 35, size: 2, prefer: ["egg", "sausage", "milk", "bread"], quote: "Món rẻ thôi." },
  { name: "Người già", avatar: "👴", mood: "Chậm rãi", patience: 45, size: 2, prefer: ["salmon", "egg", "headBone", "yogurt"], quote: "Cho tôi đồ dễ ăn." },
  { name: "Streamer", avatar: "🎥", mood: "Content", patience: 20, size: 3, prefer: ["salmon", "beef", "sausage", "strawberry"], quote: "Làm nhanh tôi còn lên sóng." },
  { name: "Cặp đôi", avatar: "💑", mood: "Hẹn hò", patience: 30, size: 3, prefer: ["cherry", "grape", "salmon", "cheese", "strawberry"], quote: "Đồ romantic nhé." },
  { name: "Shipper app", avatar: "🛵", mood: "Đơn online", patience: 17, size: 3, prefer: ["salmon", "beef", "egg", "sausage", "milk"], quote: "Đơn app đang chờ, đóng nhanh giúp em." },
  { name: "Team party", avatar: "🎉", mood: "Mua tiệc", patience: 23, size: 5, prefer: ["beef", "salmon", "cherry", "grape", "shrimp", "cheese"], quote: "Tối nay party, lấy nhiều đồ ngon nhé." },
  { name: "Khách Nhật", avatar: "🍣", mood: "Mê cá hồi", patience: 26, size: 3, prefer: ["salmon", "wholeSalmon", "squid", "cod"], quote: "Cá hồi ngon là được." },
  { name: "Nhà hàng", avatar: "🏮", mood: "Lấy sỉ", patience: 20, size: 4, prefer: ["wholeSalmon", "salmon", "beef", "shrimp", "oyster"], quote: "Cho cá nguyên con đẹp nhé." },
  { name: "Khách nấu lẩu", avatar: "🍲", mood: "Mua xương", patience: 32, size: 2, prefer: ["headBone", "beef", "salmon", "pork"], quote: "Có đầu xương nấu lẩu không?" },
  { name: "Khách Hàn", avatar: "🇰🇷", mood: "K-food", patience: 27, size: 3, prefer: ["beef", "pork", "sashimi", "bacon", "egg"], quote: "삼겹살 있어요? Thịt ba chỉ đi nha." },
  { name: "Bà nội trợ VIP", avatar: "👒", mood: "Sành điệu", patience: 22, size: 4, prefer: ["wagyu", "cheese", "scallop", "salmon", "crab"], quote: "Tôi chỉ lấy hàng xịn thôi nhé." },
  { name: "Đầu bếp", avatar: "👨‍🍳", mood: "Chuyên nghiệp", patience: 24, size: 4, prefer: ["wholeSalmon", "oyster", "crab", "cod", "scallop"], quote: "Hàng tươi sống thôi, đừng đông lạnh." },
  { name: "Nhóm sinh nhật", avatar: "🎂", mood: "Ăn tiệc", patience: 28, size: 5, prefer: ["strawberry", "cherry", "grape", "cheese", "salmon"], quote: "Hôm nay sinh nhật bạn tớ, lấy đẹp đẹp nhé!" },
  { name: "Gym girl", avatar: "🏋️‍♀️", mood: "Healthy", patience: 33, size: 3, prefer: ["blueberry", "avocado", "yogurt", "egg", "salmon"], quote: "Đồ ăn clean cho chị nhé, không chất béo." },
  { name: "Ông chủ quán", avatar: "🧔", mood: "Lấy sỉ", patience: 21, size: 4, prefer: ["wholeSalmon", "beef", "pork", "shrimp", "egg"], quote: "Lấy nhiều, tính giá tốt nhé." },
  { name: "Khách du lịch", avatar: "🧳", mood: "Ghé nhanh", patience: 15, size: 2, prefer: ["sausage", "cheese", "bread", "milk", "grape"], quote: "Mua nhanh thôi, tôi còn bắt xe." },
];

const EXPANDED_CUSTOMER_TYPES: CustomerType[] = [
  { name: "KOL ẩm thực", avatar: "📸", mood: "Review", patience: 18, size: 3, prefer: ["sashimi", "wagyu", "scallop", "cherry", "strawberry"], quote: "Món nào lên hình đẹp nhất shop?" },
  { name: "Biker đêm", avatar: "🏍️", mood: "Gấp", patience: 14, size: 2, prefer: ["sausage", "bread", "milk", "bacon"], quote: "Gói nhanh giúp anh, còn đi giao tiếp." },
  { name: "Cô giáo mầm non", avatar: "👩‍🏫", mood: "Dịu dàng", patience: 38, size: 3, prefer: ["egg", "milk", "yogurt", "bread", "orange"], quote: "Chọn đồ dễ ăn cho các bé nha." },
  { name: "Bố bỉm sữa", avatar: "🍼", mood: "Mệt nhưng vui", patience: 25, size: 4, prefer: ["milk", "egg", "salmon", "yogurt", "bread"], quote: "Món nào nhanh nấu nhất lấy giúp anh." },
  { name: "Dân IT", avatar: "💻", mood: "Cú đêm", patience: 29, size: 2, prefer: ["pizza", "sausage", "milk", "blueberry"], quote: "Đồ ăn nhanh để còn deploy." },
  { name: "Thiếu gia", avatar: "🕶️", mood: "Sang", patience: 20, size: 5, prefer: ["wagyu", "crab", "scallop", "cherry", "boCanada"], quote: "Không cần rẻ, cần ngon." },
  { name: "Chị kế toán", avatar: "🧾", mood: "Tính kỹ", patience: 31, size: 3, prefer: ["egg", "bread", "milk", "beef", "orange"], quote: "Cho chị bill gọn, hàng đúng giá nha." },
  { name: "Anh bảo vệ", avatar: "🧢", mood: "No lâu", patience: 34, size: 3, prefer: ["bread", "egg", "sausage", "pork", "milk"], quote: "Ca trực dài, lấy món chắc bụng." },
  { name: "Barista", avatar: "☕", mood: "Tinh tế", patience: 27, size: 2, prefer: ["milk", "cheese", "butter", "strawberry", "blueberry"], quote: "Đồ dairy tươi là được." },
  { name: "Chủ homestay", avatar: "🏡", mood: "Chuẩn bị bữa", patience: 26, size: 5, prefer: ["egg", "bread", "bacon", "ham", "orange"], quote: "Mai có khách lưu trú, lấy đồ ăn sáng." },
  { name: "Mẹ bầu", avatar: "🤰", mood: "Cẩn thận", patience: 37, size: 2, prefer: ["salmon", "milk", "egg", "yogurt", "avocado"], quote: "Chọn giúp đồ tươi và lành nha." },
  { name: "Fan sashimi", avatar: "🍱", mood: "Mê Nhật", patience: 24, size: 3, prefer: ["sashimi", "salmon", "cod", "scallop"], quote: "Sashimi còn set đẹp không?" },
  { name: "Tín đồ BBQ", avatar: "🔥", mood: "Nướng", patience: 22, size: 5, prefer: ["beef", "pork", "bacon", "wagyu", "sausage"], quote: "Tối nay nướng, thịt phải đã." },
  { name: "Khách keto", avatar: "🥗", mood: "Low carb", patience: 32, size: 3, prefer: ["beef", "egg", "salmon", "avocado", "cheese"], quote: "Không tinh bột, ưu tiên protein." },
  { name: "Bé thích trứng", avatar: "🧒", mood: "Háo hức", patience: 40, size: 2, prefer: ["egg", "sausage", "milk", "yogurt"], quote: "Con muốn trứng với xúc xích!" },
  { name: "Cô bán bánh", avatar: "🥐", mood: "Làm mẻ mới", patience: 28, size: 4, prefer: ["butter", "milk", "cheese", "strawberry", "blueberry"], quote: "Lấy nguyên liệu làm bánh sáng mai." },
  { name: "Chủ tiệm mì", avatar: "🍜", mood: "Nước dùng", patience: 23, size: 4, prefer: ["headBone", "beef", "pork", "egg", "shrimp"], quote: "Có xương ngon để hầm nước không?" },
  { name: "Dân chạy deadline", avatar: "⏱️", mood: "Vội", patience: 13, size: 2, prefer: ["pizza", "bread", "sausage", "milk"], quote: "Cứ món nhanh nhất mà lấy." },
  { name: "Đạo diễn quảng cáo", avatar: "🎬", mood: "Cầu kỳ", patience: 21, size: 4, prefer: ["cherry", "strawberry", "wagyu", "sashimi", "scallop"], quote: "Đồ phải nhìn premium để quay." },
  { name: "Hội picnic", avatar: "🧺", mood: "Ngoài trời", patience: 30, size: 5, prefer: ["bread", "ham", "cheese", "grape", "orange"], quote: "Đi picnic nên lấy đồ dễ chia." },
  { name: "Khách Tây", avatar: "🌍", mood: "Khám phá", patience: 26, size: 3, prefer: ["beef", "cheese", "bread", "salmon", "mango"], quote: "Recommend local best sellers, please." },
  { name: "Khách Pháp", avatar: "🇫🇷", mood: "Bơ sữa", patience: 29, size: 3, prefer: ["butter", "cheese", "bread", "salmon", "cherry"], quote: "Bơ và phô mai loại ngon nhé." },
  { name: "Khách Ý", avatar: "🇮🇹", mood: "Pasta night", patience: 28, size: 4, prefer: ["cheese", "ham", "bacon", "pizza", "orange"], quote: "Tối nay làm đồ Ý, lấy topping ngon." },
  { name: "Khách Singapore", avatar: "🇸🇬", mood: "Hải sản", patience: 25, size: 4, prefer: ["crab", "shrimp", "oyster", "squid", "scallop"], quote: "Seafood fresh không?" },
  { name: "Khách Thái", avatar: "🇹🇭", mood: "Đậm vị", patience: 26, size: 3, prefer: ["shrimp", "squid", "mango", "pork", "egg"], quote: "Lấy đồ làm món chua cay nha." },
  { name: "Bếp chay linh hoạt", avatar: "🥑", mood: "Nhẹ nhàng", patience: 36, size: 3, prefer: ["avocado", "grape", "kiwi", "mango", "yogurt"], quote: "Hôm nay ưu tiên trái cây và sữa chua." },
  { name: "Chú tài xế", avatar: "🚕", mood: "Tranh thủ", patience: 16, size: 2, prefer: ["bread", "sausage", "milk", "egg"], quote: "Đang đợi khách, làm nhanh giúp chú." },
  { name: "Designer", avatar: "🎨", mood: "Đẹp mắt", patience: 27, size: 3, prefer: ["cherry", "blueberry", "strawberry", "sashimi", "cheese"], quote: "Màu món phải xinh nha." },
  { name: "Producer âm nhạc", avatar: "🎧", mood: "Studio", patience: 24, size: 3, prefer: ["pizza", "bacon", "milk", "grape"], quote: "Ăn trong phòng thu, gọn thôi." },
  { name: "Nhiếp ảnh gia", avatar: "📷", mood: "Canh sáng", patience: 19, size: 2, prefer: ["sashimi", "cherry", "scallop", "salmon"], quote: "Đồ tươi nhìn lên ảnh mới đẹp." },
  { name: "Cô yoga", avatar: "🧘‍♀️", mood: "Cân bằng", patience: 39, size: 2, prefer: ["yogurt", "blueberry", "avocado", "salmon", "kiwi"], quote: "Lấy đồ nhẹ bụng sau buổi tập." },
  { name: "Anh marathon", avatar: "🏃", mood: "Nạp năng lượng", patience: 30, size: 4, prefer: ["egg", "bread", "beef", "orange"], quote: "Cần món giàu năng lượng nhưng dễ ăn." },
  { name: "Chị spa", avatar: "💅", mood: "Healthy", patience: 34, size: 3, prefer: ["kiwi", "strawberry", "blueberry", "yogurt", "salmon"], quote: "Đồ đẹp da chút nha." },
  { name: "Chủ phòng gym", avatar: "🏋️", mood: "Mua theo gói", patience: 23, size: 5, prefer: ["beef", "egg", "salmon", "yogurt"], quote: "Lấy nhiều protein cho hội tập." },
  { name: "Cậu học sinh", avatar: "🎒", mood: "Ăn vặt", patience: 33, size: 2, prefer: ["sausage", "milk", "bread", "yogurt"], quote: "Món nào ăn sau giờ học được ạ?" },
  { name: "Cô thủ thư", avatar: "📚", mood: "Yên tĩnh", patience: 44, size: 2, prefer: ["milk", "bread", "cheese", "grape"], quote: "Không cần vội, chọn đồ nhẹ thôi." },
  { name: "Ông hàng xóm", avatar: "🏘️", mood: "Quen mặt", patience: 41, size: 3, prefer: ["headBone", "egg", "pork", "orange"], quote: "Như mọi hôm, lấy đồ nấu canh." },
  { name: "Cô hàng xóm", avatar: "🌷", mood: "Thân thiện", patience: 42, size: 3, prefer: ["salmon", "egg", "grape", "milk"], quote: "Có gì tươi mới để cô thử không?" },
  { name: "Chủ quán nhậu", avatar: "🍻", mood: "Lấy mồi", patience: 20, size: 5, prefer: ["squid", "shrimp", "pork", "bacon", "sausage"], quote: "Tối nay đông bàn, lấy mồi ngon." },
  { name: "Hội xem bóng", avatar: "⚽", mood: "Đông vui", patience: 24, size: 5, prefer: ["pizza", "sausage", "bacon", "bread", "grape"], quote: "Có trận lớn, đồ ăn phải đủ chia." },
  { name: "Fan hải sản", avatar: "🦞", mood: "Tươi sống", patience: 23, size: 4, prefer: ["crab", "oyster", "shrimp", "scallop", "squid"], quote: "Hải sản hôm nay con nào ngon?" },
  { name: "Fan thịt đỏ", avatar: "🥩", mood: "Đậm đà", patience: 22, size: 4, prefer: ["beef", "boCanada", "wagyu", "pork"], quote: "Thịt đỏ loại ngon nhất nhé." },
  { name: "Fan trái cây", avatar: "🍓", mood: "Ngọt mát", patience: 35, size: 3, prefer: ["cherry", "strawberry", "mango", "grape", "kiwi"], quote: "Chọn trái cây ngọt cho mình." },
  { name: "Fan đồ sữa", avatar: "🥛", mood: "Mịn màng", patience: 33, size: 3, prefer: ["milk", "yogurt", "cheese", "butter"], quote: "Đồ sữa date mới nha." },
  { name: "Người ăn sáng", avatar: "🌅", mood: "Nhanh gọn", patience: 27, size: 3, prefer: ["egg", "bread", "ham", "milk", "butter"], quote: "Combo ăn sáng nào nhanh nhất?" },
  { name: "Người ăn khuya", avatar: "🌙", mood: "Đói bụng", patience: 18, size: 3, prefer: ["pizza", "sausage", "bacon", "milk"], quote: "Đói quá, lấy gì no nhanh đi." },
  { name: "Cô văn phòng eat-clean", avatar: "🥙", mood: "Kỷ luật", patience: 31, size: 3, prefer: ["salmon", "avocado", "yogurt", "blueberry"], quote: "Meal prep tuần này nhẹ thôi." },
  { name: "Anh sales", avatar: "🤝", mood: "Linh hoạt", patience: 21, size: 3, prefer: ["bread", "ham", "cheese", "orange"], quote: "Có gì ăn trên đường được không?" },
  { name: "Cô livestream", avatar: "📱", mood: "Tương tác", patience: 17, size: 3, prefer: ["cherry", "sashimi", "wagyu", "strawberry"], quote: "Khán giả đang chọn món cho mình." },
  { name: "Chủ bếp Âu", avatar: "🍽️", mood: "Chuẩn vị", patience: 23, size: 4, prefer: ["boCanada", "butter", "cheese", "scallop", "cod"], quote: "Lấy nguyên liệu kiểu Âu nhé." },
  { name: "Chủ bếp Á", avatar: "🥢", mood: "Nước sốt", patience: 24, size: 4, prefer: ["salmon", "squid", "shrimp", "pork", "egg"], quote: "Đồ làm món Á phải tươi." },
  { name: "Quản lý khách sạn", avatar: "🏨", mood: "Ổn định", patience: 25, size: 5, prefer: ["egg", "bread", "ham", "bacon", "milk"], quote: "Lấy đồ buffet sáng cho khách." },
  { name: "Chủ căn tin", avatar: "🏫", mood: "Số lượng", patience: 22, size: 5, prefer: ["egg", "sausage", "bread", "milk", "orange"], quote: "Cần món dễ bán cho giờ ra chơi." },
  { name: "Nhân viên ngân hàng", avatar: "🏦", mood: "Lịch sự", patience: 28, size: 3, prefer: ["salmon", "beef", "grape", "yogurt"], quote: "Gói đẹp giúp tôi mang về văn phòng." },
  { name: "Cô florist", avatar: "💐", mood: "Tinh tế", patience: 32, size: 2, prefer: ["strawberry", "cherry", "kiwi", "cheese"], quote: "Món nào nhìn thanh lịch nhất?" },
  { name: "Anh kỹ sư", avatar: "🛠️", mood: "Thực tế", patience: 30, size: 3, prefer: ["beef", "egg", "bread", "pork"], quote: "Cứ món chắc bụng, dễ nấu." },
  { name: "Bác sĩ trực", avatar: "🩺", mood: "Ít thời gian", patience: 16, size: 2, prefer: ["salmon", "yogurt", "bread", "milk"], quote: "Tôi còn ca trực, làm nhanh giúp." },
  { name: "Dược sĩ", avatar: "💊", mood: "Kỹ lưỡng", patience: 34, size: 2, prefer: ["yogurt", "milk", "egg", "orange"], quote: "Đồ tươi và hạn dùng rõ nha." },
  { name: "Chủ tiệm hoa quả", avatar: "🍊", mood: "Chọn kỹ", patience: 30, size: 4, prefer: ["grape", "cherry", "mango", "orange", "kiwi"], quote: "Trái đẹp để bày quầy nhé." },
  { name: "Đội cắm trại", avatar: "⛺", mood: "Chuẩn bị xa", patience: 27, size: 5, prefer: ["sausage", "bread", "bacon", "egg", "orange"], quote: "Đi cắm trại nên cần đồ dễ bảo quản." },
  { name: "Chị làm bánh healthy", avatar: "🧁", mood: "Ít ngọt", patience: 33, size: 3, prefer: ["blueberry", "yogurt", "milk", "strawberry", "butter"], quote: "Lấy nguyên liệu làm bánh healthy." },
  { name: "Anh pha chế", avatar: "🍹", mood: "Pha mix", patience: 26, size: 3, prefer: ["orange", "mango", "kiwi", "strawberry", "milk"], quote: "Trái cây để pha đồ uống nha." },
  { name: "Nhóm workshop", avatar: "🧑‍💼", mood: "Teabreak", patience: 28, size: 5, prefer: ["bread", "cheese", "ham", "grape", "yogurt"], quote: "Teabreak cần gọn và đẹp." },
  { name: "Cô mẫu ảnh", avatar: "💃", mood: "Giữ dáng", patience: 31, size: 2, prefer: ["salmon", "blueberry", "kiwi", "yogurt"], quote: "Nhẹ bụng nhưng vẫn ngon nha." },
  { name: "Anh quay phim", avatar: "🎞️", mood: "Mang set", patience: 20, size: 3, prefer: ["bread", "sausage", "milk"], quote: "Ăn nhanh trên set quay thôi." },
  { name: "Cô chủ shop online", avatar: "📦", mood: "Đóng đơn", patience: 19, size: 3, prefer: ["milk", "bread", "egg", "grape"], quote: "Shop đang nhiều đơn, làm gọn nha." },
  { name: "Gia đình trẻ", avatar: "👨‍👩‍👦", mood: "Bữa tối", patience: 32, size: 5, prefer: ["salmon", "beef", "egg", "orange"], quote: "Tối nay nấu bữa gia đình." },
  { name: "Chú hàng xóm khó tính", avatar: "🧓", mood: "Soi giá", patience: 20, size: 2, prefer: ["egg", "headBone", "pork", "bread"], quote: "Đừng cân thiếu cho chú nha." },
  { name: "Đầu bếp tiệc cưới", avatar: "💒", mood: "Đặt nhiều", patience: 22, size: 5, prefer: ["crab", "shrimp", "beef", "scallop", "cherry"], quote: "Tiệc cưới cần hàng đồng đều." },
  { name: "Quán salad", avatar: "🥗", mood: "Tươi xanh", patience: 29, size: 4, prefer: ["avocado", "kiwi", "strawberry", "salmon", "cheese"], quote: "Salad hôm nay cần topping xịn." },
  { name: "Quán sushi nhỏ", avatar: "🍣", mood: "Tỉ mỉ", patience: 22, size: 4, prefer: ["salmon", "sashimi", "cod", "shrimp", "avocado"], quote: "Cá phải cắt lên đẹp." },
  { name: "Tiệm steak", avatar: "🍖", mood: "Lửa lớn", patience: 21, size: 5, prefer: ["beef", "boCanada", "wagyu", "butter", "pork"], quote: "Steak tối nay cần thịt chuẩn." },
  { name: "Bếp gia đình đông con", avatar: "👨‍👩‍👧‍👦", mood: "Mua nhiều", patience: 35, size: 5, prefer: ["egg", "sausage", "beef", "milk", "bread"], quote: "Nhà đông người nên lấy nhiều chút." },
  { name: "Cặp đôi mới cưới", avatar: "💍", mood: "Tập nấu", patience: 36, size: 2, prefer: ["salmon", "beef", "cheese", "strawberry"], quote: "Tụi mình mới tập nấu, chọn dễ làm nha." },
  { name: "Chuyên gia dinh dưỡng", avatar: "📋", mood: "Cân đối", patience: 34, size: 3, prefer: ["salmon", "egg", "avocado", "yogurt", "blueberry"], quote: "Tôi cần một giỏ đủ đạm và vitamin." },
];

export const CUSTOMER_TYPES: CustomerType[] = [...BASE_CUSTOMER_TYPES, ...EXPANDED_CUSTOMER_TYPES];

export const SHOP_EVENTS: ShopEvent[] = [
  { id: "staff-off", type: "bad", title: "Nhân viên nghỉ đột xuất", description: "😴 Nhân viên gọi báo ốm sáng nay. Khách dễ sốt ruột hơn — mood đầu ngày -10 điểm.", moodDelta: -10 },
  { id: "thief", type: "bad", title: "Bị trộm vặt", description: "🦹 Có kẻ lén lút móc tiền quầy thu ngân. Mất tiền mặt.", cashDelta: -150 },
  { id: "freezer-issue", type: "bad", title: "Tủ đông trục trặc", description: "🌡️ Tủ đông mất điện một lúc. Bò Mỹ và cá hồi bị hao hụt nhẹ.", stockDelta: { salmon: -0.5, beef: -0.5 } },
  { id: "viral-post", type: "good", title: "Bài TikTok viral", description: "📱✨ Video check-in cửa hàng lan truyền mạng xã hội! +100k tiền mặt và mood đầu ngày +8.", cashDelta: 100, moodDelta: 8 },
  { id: "supplier-bonus", type: "good", title: "Nhà cung cấp tặng hàng", description: "📦🎁 Nhà cung cấp gửi quà tri ân, kho thêm một ít hàng.", stockDelta: { egg: 3, sausage: 3 } },
  { id: "loyal-customer", type: "good", title: "Khách quen ghé sớm", description: "🤝 Một nhóm khách quen tới sớm, vui vẻ và chi thoải mái. Mood đầu ngày +12.", moodDelta: 12 },
  { id: "rainy-day", type: "neutral", title: "Trời mưa", description: "🌧️ Trời đổ mưa to, khách ngại ra đường — đơn app tăng vọt nhưng khách vội hơn. Mood đầu ngày -4.", moodDelta: -4 },
];

export const MASCOT_ASSETS: Record<MascotState, string> = {
  idle: "/homefarm-shop/mascot/trust-me.webp",
  happy: "/homefarm-shop/mascot/sieu-vui.webp",
  combo: "/homefarm-shop/mascot/dab.webp",
  wrong: "/homefarm-shop/mascot/ngac-nhien.webp",
  hurry: "/homefarm-shop/mascot/thong-bao.webp",
  fail: "/homefarm-shop/mascot/buon-va-bat-luc.webp",
  idea: "/homefarm-shop/mascot/y-tuong.webp",
  thinking: "/homefarm-shop/mascot/suy-ngam.webp",
  trust: "/homefarm-shop/mascot/tin-tuong.webp",
};

export const MASCOT_TALK: Record<MascotState, string> = {
  idle: "Có khách kìa!",
  happy: "Chuẩn rồi bro!",
  combo: "Combo cháy quá!",
  wrong: "Ơ sai món rồi!",
  hurry: "Nhanh lên nào!",
  fail: "Toang mất khách rồi...",
  idea: "Hint: nhìn ORDER nhé!",
  thinking: "Tính kỹ chút nha.",
  trust: "Tin tớ, món này bán chạy!",
};

export const ACHIEVEMENTS: Achievement[] = [
  { id: "first_serve", title: "Khởi nghiệp!", desc: "Phục vụ khách hàng đầu tiên", icon: "🎉" },
  { id: "combo_5", title: "Tốc độ ánh sáng", desc: "Đạt combo x5", icon: "⚡" },
  { id: "combo_10", title: "Combo Cháy", desc: "Đạt combo x10", icon: "🔥" },
  { id: "perfect_day", title: "Ngày hoàn hảo", desc: "0 khách bỏ qua trong 1 ngày (≥5 khách)", icon: "⭐" },
  { id: "big_revenue", title: "Ngày thắng lớn", desc: "Doanh thu 1 ngày đạt 10.000k", icon: "💰" },
  { id: "order_2000", title: "Đơn khủng!!!", desc: "Hoàn thành đơn hàng đạt 2.000k", icon: "🧾" },
  { id: "order_5000", title: "Khách sộp ghé thăm", desc: "Hoàn thành đơn hàng đạt 5.000k", icon: "💎" },
  { id: "order_10000", title: "Thần tài tới, thần tài tới", desc: "Hoàn thành đơn hàng đạt 10.000k", icon: "🧧" },
  { id: "first_tip", title: "Bo nhẹ lấy vía", desc: "Nhận tip lần đầu tiên", icon: "🪙" },
  { id: "tip_200", title: "Khách thương quá trời", desc: "Nhận tip từ một đơn đạt 200k", icon: "💌" },
  { id: "total_tip_2000", title: "Vua săn tip", desc: "Tích lũy tổng tip đạt 2.000k", icon: "👑" },
  { id: "total_100", title: "Chủ shop chăm chỉ", desc: "Phục vụ tổng 100 khách", icon: "🤝" },
  { id: "millionaire", title: "Tỷ phú mini", desc: "Tích lũy 50.000k tiền mặt", icon: "🏆" },
  { id: "salmon_master",   title: "Vua cá hồi",       desc: "Bán 50kg cá hồi trong 1 ngày",                      icon: "🐟" },
  { id: "bulk_save_200",  title: "Biết tính toán",   desc: "Tiết kiệm tích lũy 200k nhờ nhập số lượng lớn",    icon: "🧮" },
  { id: "bulk_save_500",  title: "Mua hàng khôn",    desc: "Tiết kiệm tích lũy 500k nhờ nhập số lượng lớn",    icon: "💡" },
  { id: "bulk_save_1000", title: "Thánh nhập hàng",  desc: "Tiết kiệm tích lũy 1.000k nhờ nhập số lượng lớn", icon: "📦" },
  { id: "bulk_save_1500", title: "Vua mua sỉ",       desc: "Tiết kiệm tích lũy 1.500k nhờ nhập số lượng lớn", icon: "👑" },
  { id: "bulk_save_2000",  title: "Thánh tiết kiệm",  desc: "Tiết kiệm tích lũy 2.000k nhờ nhập số lượng lớn",          icon: "🪙" },
  { id: "sold_salmon_100",  title: "Người cá",         desc: "Bán tích lũy 100kg cá hồi",                               icon: "🧜" },
  { id: "sold_beef_100",    title: "Vua bò",           desc: "Bán tích lũy 100kg bò các loại",                          icon: "🐄" },
  { id: "sold_pork_100",    title: "Đại gia heo",      desc: "Bán tích lũy 100 phần heo, bacon, jambon",                icon: "🐷" },
  { id: "sold_egg_50",      title: "Con gà vàng",      desc: "Bán tích lũy 50 hộp trứng",                               icon: "🐓" },
  { id: "sold_shrimp_50",   title: "Vua tôm",          desc: "Bán tích lũy 50kg tôm",                                   icon: "🦐" },
  { id: "sold_sashimi_30",  title: "Đầu bếp Nhật",    desc: "Bán tích lũy 30 set sashimi",                             icon: "🍣" },
  { id: "sold_fruit_100",   title: "Thần hoa quả",     desc: "Bán tích lũy 100kg/hộp trái cây các loại",               icon: "🍇" },
  { id: "sold_seafood_200", title: "Vua hải sản",      desc: "Bán tích lũy 200kg hải sản tổng",                        icon: "🦞" },
  { id: "sold_meat_200",    title: "Thánh thịt",       desc: "Bán tích lũy 200kg thịt tổng",                           icon: "🥩" },
  { id: "sold_dairy_100",   title: "Chủ trang trại",   desc: "Bán tích lũy 100 sản phẩm sữa (milk, yogurt, cheese, butter)", icon: "🥛" },
];
